# Generated by Django 4.1.4 on 2024-04-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=20)),
            ],
        ),
    ]
