# Generated by Django 4.1.4 on 2024-04-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCPGI', '0002_login1'),
    ]

    operations = [
        migrations.CreateModel(
            name='complain1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.CharField(max_length=100)),
                ('place', models.EmailField(max_length=200)),
                ('email', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('file', models.CharField(max_length=200)),
            ],
        ),
    ]
