# Generated by Django 4.1.4 on 2024-04-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCPGI', '0003_complain1'),
    ]

    operations = [
        migrations.CreateModel(
            name='sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='complain1',
        ),
        migrations.DeleteModel(
            name='login1',
        ),
        migrations.DeleteModel(
            name='signup1',
        ),
    ]
